/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.kt.app

data class UserAPIs(private val repository: UserRepository) {

    fun getById(id: Int): User {
        return repository.getById(id)
    }
}

fun main() {
}
